GENOME_FA = '/home/cmb-panasas2/skchoudh/genomes/ASM584v2/fasta/Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.dna.toplevel.cleaned.fa'
CHROM_SIZES = '/home/cmb-panasas2/skchoudh/genomes/ASM584v2/fasta/Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.dna.toplevel.sizes'
GENMAP_INDEX_PREFIX = 'genmap_index'
GENMAP_INDEX = GENMAP_INDEX_PREFIX + '/' + 'index.rev.lf.drp'
GENMAP_OUT_DIR = '/home/cmb-panasas2/skchoudh/genomes/ASM584v2/genmap'
