GENOME_FA = '/home/cmb-panasas2/skchoudh/genomes/GRCg6/fasta/Gallus_gallus.GRCg6a.dna.toplevel.cleaned.fa'
CHROM_SIZES = '/home/cmb-panasas2/skchoudh/genomes/GRCg6/fasta/Gallus_gallus.GRCg6a.dna.toplevel.sizes'
GENMAP_INDEX_PREFIX = 'genmap_index'
GENMAP_INDEX = GENMAP_INDEX_PREFIX + '/' + 'index.rev.lf.drp'
GENMAP_OUT_DIR = '/home/cmb-panasas2/skchoudh/genomes/GRCg6/genmap'
GEM_INDEX_PREFIX = 'GRCg6_gem_index'
GEM_INDEX = 'GRCg6_gem_index.gem'
TMPDIR = '/staging/as/skchoudh/'
