GENOME_FA = '/home/cmb-panasas2/skchoudh/genomes/panTro3/fasta/Pan_troglodytes.Pan_tro_3.0.dna.toplevel.cleaned.fa'
CHROM_SIZES = '/home/cmb-panasas2/skchoudh/genomes/panTro3/fasta/Pan_troglodytes.Pan_tro_3.0.dna.toplevel.sizes'
GENMAP_INDEX_PREFIX = 'genmap_index'
GENMAP_INDEX = GENMAP_INDEX_PREFIX + '/' + 'index.rev.lf.drp'
GENMAP_OUT_DIR = '/home/cmb-panasas2/skchoudh/genomes/panTro3//genmap'
TMPDIR = '/staging/as/skchoudh/genmap_panTro3_tmp/'
