GENOME_FA = '/home/cmb-panasas2/skchoudh/genomes/Rnor6.0/fasta/Rattus_norvegicus.Rnor_6.0.dna.toplevel.cleaned.fa'
CHROM_SIZES = '/home/cmb-panasas2/skchoudh/genomes/Rnor6.0/fasta/Rattus_norvegicus.Rnor_6.0.dna.toplevel.sizes'
GENMAP_INDEX_PREFIX = 'genmap_index'
GENMAP_INDEX = GENMAP_INDEX_PREFIX + '/' + 'index.rev.lf.drp'
GENMAP_OUT_DIR = '/home/cmb-panasas2/skchoudh/genomes/Rnor6.0/genmap'
TMPDIR = '/staging/as/skchoudh/genmap_Rnor6_tmp/'
